# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/e/Progetti/Project_Omega

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/e/Progetti/Project_Omega

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/e/Progetti/Project_Omega/CMakeFiles /mnt/e/Progetti/Project_Omega/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/e/Progetti/Project_Omega/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named kernel

# Build rule for target.
kernel: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kernel
.PHONY : kernel

# fast build rule for target.
kernel/fast:
	$(MAKE) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/build
.PHONY : kernel/fast

src/kernel/IDT/IDT.o: src/kernel/IDT/IDT.cpp.o

.PHONY : src/kernel/IDT/IDT.o

# target to build an object file
src/kernel/IDT/IDT.cpp.o:
	$(MAKE) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/kernel/IDT/IDT.cpp.o
.PHONY : src/kernel/IDT/IDT.cpp.o

src/kernel/IDT/IDT.i: src/kernel/IDT/IDT.cpp.i

.PHONY : src/kernel/IDT/IDT.i

# target to preprocess a source file
src/kernel/IDT/IDT.cpp.i:
	$(MAKE) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/kernel/IDT/IDT.cpp.i
.PHONY : src/kernel/IDT/IDT.cpp.i

src/kernel/IDT/IDT.s: src/kernel/IDT/IDT.cpp.s

.PHONY : src/kernel/IDT/IDT.s

# target to generate assembly for a file
src/kernel/IDT/IDT.cpp.s:
	$(MAKE) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/kernel/IDT/IDT.cpp.s
.PHONY : src/kernel/IDT/IDT.cpp.s

src/kernel/IDT/Keyboard/KBScanCode.o: src/kernel/IDT/Keyboard/KBScanCode.cpp.o

.PHONY : src/kernel/IDT/Keyboard/KBScanCode.o

# target to build an object file
src/kernel/IDT/Keyboard/KBScanCode.cpp.o:
	$(MAKE) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/kernel/IDT/Keyboard/KBScanCode.cpp.o
.PHONY : src/kernel/IDT/Keyboard/KBScanCode.cpp.o

src/kernel/IDT/Keyboard/KBScanCode.i: src/kernel/IDT/Keyboard/KBScanCode.cpp.i

.PHONY : src/kernel/IDT/Keyboard/KBScanCode.i

# target to preprocess a source file
src/kernel/IDT/Keyboard/KBScanCode.cpp.i:
	$(MAKE) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/kernel/IDT/Keyboard/KBScanCode.cpp.i
.PHONY : src/kernel/IDT/Keyboard/KBScanCode.cpp.i

src/kernel/IDT/Keyboard/KBScanCode.s: src/kernel/IDT/Keyboard/KBScanCode.cpp.s

.PHONY : src/kernel/IDT/Keyboard/KBScanCode.s

# target to generate assembly for a file
src/kernel/IDT/Keyboard/KBScanCode.cpp.s:
	$(MAKE) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/kernel/IDT/Keyboard/KBScanCode.cpp.s
.PHONY : src/kernel/IDT/Keyboard/KBScanCode.cpp.s

src/kernel/IDT/Keyboard/Keyboard.o: src/kernel/IDT/Keyboard/Keyboard.cpp.o

.PHONY : src/kernel/IDT/Keyboard/Keyboard.o

# target to build an object file
src/kernel/IDT/Keyboard/Keyboard.cpp.o:
	$(MAKE) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/kernel/IDT/Keyboard/Keyboard.cpp.o
.PHONY : src/kernel/IDT/Keyboard/Keyboard.cpp.o

src/kernel/IDT/Keyboard/Keyboard.i: src/kernel/IDT/Keyboard/Keyboard.cpp.i

.PHONY : src/kernel/IDT/Keyboard/Keyboard.i

# target to preprocess a source file
src/kernel/IDT/Keyboard/Keyboard.cpp.i:
	$(MAKE) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/kernel/IDT/Keyboard/Keyboard.cpp.i
.PHONY : src/kernel/IDT/Keyboard/Keyboard.cpp.i

src/kernel/IDT/Keyboard/Keyboard.s: src/kernel/IDT/Keyboard/Keyboard.cpp.s

.PHONY : src/kernel/IDT/Keyboard/Keyboard.s

# target to generate assembly for a file
src/kernel/IDT/Keyboard/Keyboard.cpp.s:
	$(MAKE) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/kernel/IDT/Keyboard/Keyboard.cpp.s
.PHONY : src/kernel/IDT/Keyboard/Keyboard.cpp.s

src/kernel/IO.o: src/kernel/IO.cpp.o

.PHONY : src/kernel/IO.o

# target to build an object file
src/kernel/IO.cpp.o:
	$(MAKE) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/kernel/IO.cpp.o
.PHONY : src/kernel/IO.cpp.o

src/kernel/IO.i: src/kernel/IO.cpp.i

.PHONY : src/kernel/IO.i

# target to preprocess a source file
src/kernel/IO.cpp.i:
	$(MAKE) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/kernel/IO.cpp.i
.PHONY : src/kernel/IO.cpp.i

src/kernel/IO.s: src/kernel/IO.cpp.s

.PHONY : src/kernel/IO.s

# target to generate assembly for a file
src/kernel/IO.cpp.s:
	$(MAKE) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/kernel/IO.cpp.s
.PHONY : src/kernel/IO.cpp.s

src/kernel/MEM/Heap.o: src/kernel/MEM/Heap.cpp.o

.PHONY : src/kernel/MEM/Heap.o

# target to build an object file
src/kernel/MEM/Heap.cpp.o:
	$(MAKE) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/kernel/MEM/Heap.cpp.o
.PHONY : src/kernel/MEM/Heap.cpp.o

src/kernel/MEM/Heap.i: src/kernel/MEM/Heap.cpp.i

.PHONY : src/kernel/MEM/Heap.i

# target to preprocess a source file
src/kernel/MEM/Heap.cpp.i:
	$(MAKE) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/kernel/MEM/Heap.cpp.i
.PHONY : src/kernel/MEM/Heap.cpp.i

src/kernel/MEM/Heap.s: src/kernel/MEM/Heap.cpp.s

.PHONY : src/kernel/MEM/Heap.s

# target to generate assembly for a file
src/kernel/MEM/Heap.cpp.s:
	$(MAKE) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/kernel/MEM/Heap.cpp.s
.PHONY : src/kernel/MEM/Heap.cpp.s

src/kernel/MEM/Memory.o: src/kernel/MEM/Memory.cpp.o

.PHONY : src/kernel/MEM/Memory.o

# target to build an object file
src/kernel/MEM/Memory.cpp.o:
	$(MAKE) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/kernel/MEM/Memory.cpp.o
.PHONY : src/kernel/MEM/Memory.cpp.o

src/kernel/MEM/Memory.i: src/kernel/MEM/Memory.cpp.i

.PHONY : src/kernel/MEM/Memory.i

# target to preprocess a source file
src/kernel/MEM/Memory.cpp.i:
	$(MAKE) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/kernel/MEM/Memory.cpp.i
.PHONY : src/kernel/MEM/Memory.cpp.i

src/kernel/MEM/Memory.s: src/kernel/MEM/Memory.cpp.s

.PHONY : src/kernel/MEM/Memory.s

# target to generate assembly for a file
src/kernel/MEM/Memory.cpp.s:
	$(MAKE) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/kernel/MEM/Memory.cpp.s
.PHONY : src/kernel/MEM/Memory.cpp.s

src/kernel/MEM/MemoryMap.o: src/kernel/MEM/MemoryMap.cpp.o

.PHONY : src/kernel/MEM/MemoryMap.o

# target to build an object file
src/kernel/MEM/MemoryMap.cpp.o:
	$(MAKE) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/kernel/MEM/MemoryMap.cpp.o
.PHONY : src/kernel/MEM/MemoryMap.cpp.o

src/kernel/MEM/MemoryMap.i: src/kernel/MEM/MemoryMap.cpp.i

.PHONY : src/kernel/MEM/MemoryMap.i

# target to preprocess a source file
src/kernel/MEM/MemoryMap.cpp.i:
	$(MAKE) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/kernel/MEM/MemoryMap.cpp.i
.PHONY : src/kernel/MEM/MemoryMap.cpp.i

src/kernel/MEM/MemoryMap.s: src/kernel/MEM/MemoryMap.cpp.s

.PHONY : src/kernel/MEM/MemoryMap.s

# target to generate assembly for a file
src/kernel/MEM/MemoryMap.cpp.s:
	$(MAKE) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/kernel/MEM/MemoryMap.cpp.s
.PHONY : src/kernel/MEM/MemoryMap.cpp.s

src/kernel/cpu/8259.o: src/kernel/cpu/8259.cpp.o

.PHONY : src/kernel/cpu/8259.o

# target to build an object file
src/kernel/cpu/8259.cpp.o:
	$(MAKE) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/kernel/cpu/8259.cpp.o
.PHONY : src/kernel/cpu/8259.cpp.o

src/kernel/cpu/8259.i: src/kernel/cpu/8259.cpp.i

.PHONY : src/kernel/cpu/8259.i

# target to preprocess a source file
src/kernel/cpu/8259.cpp.i:
	$(MAKE) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/kernel/cpu/8259.cpp.i
.PHONY : src/kernel/cpu/8259.cpp.i

src/kernel/cpu/8259.s: src/kernel/cpu/8259.cpp.s

.PHONY : src/kernel/cpu/8259.s

# target to generate assembly for a file
src/kernel/cpu/8259.cpp.s:
	$(MAKE) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/kernel/cpu/8259.cpp.s
.PHONY : src/kernel/cpu/8259.cpp.s

src/kernel/cpu/cpuid.o: src/kernel/cpu/cpuid.cpp.o

.PHONY : src/kernel/cpu/cpuid.o

# target to build an object file
src/kernel/cpu/cpuid.cpp.o:
	$(MAKE) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/kernel/cpu/cpuid.cpp.o
.PHONY : src/kernel/cpu/cpuid.cpp.o

src/kernel/cpu/cpuid.i: src/kernel/cpu/cpuid.cpp.i

.PHONY : src/kernel/cpu/cpuid.i

# target to preprocess a source file
src/kernel/cpu/cpuid.cpp.i:
	$(MAKE) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/kernel/cpu/cpuid.cpp.i
.PHONY : src/kernel/cpu/cpuid.cpp.i

src/kernel/cpu/cpuid.s: src/kernel/cpu/cpuid.cpp.s

.PHONY : src/kernel/cpu/cpuid.s

# target to generate assembly for a file
src/kernel/cpu/cpuid.cpp.s:
	$(MAKE) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/kernel/cpu/cpuid.cpp.s
.PHONY : src/kernel/cpu/cpuid.cpp.s

src/kernel/drivers/cmos.o: src/kernel/drivers/cmos.cpp.o

.PHONY : src/kernel/drivers/cmos.o

# target to build an object file
src/kernel/drivers/cmos.cpp.o:
	$(MAKE) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/kernel/drivers/cmos.cpp.o
.PHONY : src/kernel/drivers/cmos.cpp.o

src/kernel/drivers/cmos.i: src/kernel/drivers/cmos.cpp.i

.PHONY : src/kernel/drivers/cmos.i

# target to preprocess a source file
src/kernel/drivers/cmos.cpp.i:
	$(MAKE) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/kernel/drivers/cmos.cpp.i
.PHONY : src/kernel/drivers/cmos.cpp.i

src/kernel/drivers/cmos.s: src/kernel/drivers/cmos.cpp.s

.PHONY : src/kernel/drivers/cmos.s

# target to generate assembly for a file
src/kernel/drivers/cmos.cpp.s:
	$(MAKE) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/kernel/drivers/cmos.cpp.s
.PHONY : src/kernel/drivers/cmos.cpp.s

src/kernel/drivers/fs/disks.o: src/kernel/drivers/fs/disks.cpp.o

.PHONY : src/kernel/drivers/fs/disks.o

# target to build an object file
src/kernel/drivers/fs/disks.cpp.o:
	$(MAKE) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/kernel/drivers/fs/disks.cpp.o
.PHONY : src/kernel/drivers/fs/disks.cpp.o

src/kernel/drivers/fs/disks.i: src/kernel/drivers/fs/disks.cpp.i

.PHONY : src/kernel/drivers/fs/disks.i

# target to preprocess a source file
src/kernel/drivers/fs/disks.cpp.i:
	$(MAKE) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/kernel/drivers/fs/disks.cpp.i
.PHONY : src/kernel/drivers/fs/disks.cpp.i

src/kernel/drivers/fs/disks.s: src/kernel/drivers/fs/disks.cpp.s

.PHONY : src/kernel/drivers/fs/disks.s

# target to generate assembly for a file
src/kernel/drivers/fs/disks.cpp.s:
	$(MAKE) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/kernel/drivers/fs/disks.cpp.s
.PHONY : src/kernel/drivers/fs/disks.cpp.s

src/kernel/drivers/fs/floppy.o: src/kernel/drivers/fs/floppy.cpp.o

.PHONY : src/kernel/drivers/fs/floppy.o

# target to build an object file
src/kernel/drivers/fs/floppy.cpp.o:
	$(MAKE) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/kernel/drivers/fs/floppy.cpp.o
.PHONY : src/kernel/drivers/fs/floppy.cpp.o

src/kernel/drivers/fs/floppy.i: src/kernel/drivers/fs/floppy.cpp.i

.PHONY : src/kernel/drivers/fs/floppy.i

# target to preprocess a source file
src/kernel/drivers/fs/floppy.cpp.i:
	$(MAKE) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/kernel/drivers/fs/floppy.cpp.i
.PHONY : src/kernel/drivers/fs/floppy.cpp.i

src/kernel/drivers/fs/floppy.s: src/kernel/drivers/fs/floppy.cpp.s

.PHONY : src/kernel/drivers/fs/floppy.s

# target to generate assembly for a file
src/kernel/drivers/fs/floppy.cpp.s:
	$(MAKE) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/kernel/drivers/fs/floppy.cpp.s
.PHONY : src/kernel/drivers/fs/floppy.cpp.s

src/kernel/drivers/pit.o: src/kernel/drivers/pit.cpp.o

.PHONY : src/kernel/drivers/pit.o

# target to build an object file
src/kernel/drivers/pit.cpp.o:
	$(MAKE) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/kernel/drivers/pit.cpp.o
.PHONY : src/kernel/drivers/pit.cpp.o

src/kernel/drivers/pit.i: src/kernel/drivers/pit.cpp.i

.PHONY : src/kernel/drivers/pit.i

# target to preprocess a source file
src/kernel/drivers/pit.cpp.i:
	$(MAKE) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/kernel/drivers/pit.cpp.i
.PHONY : src/kernel/drivers/pit.cpp.i

src/kernel/drivers/pit.s: src/kernel/drivers/pit.cpp.s

.PHONY : src/kernel/drivers/pit.s

# target to generate assembly for a file
src/kernel/drivers/pit.cpp.s:
	$(MAKE) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/kernel/drivers/pit.cpp.s
.PHONY : src/kernel/drivers/pit.cpp.s

src/kernel/drivers/serial.o: src/kernel/drivers/serial.cpp.o

.PHONY : src/kernel/drivers/serial.o

# target to build an object file
src/kernel/drivers/serial.cpp.o:
	$(MAKE) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/kernel/drivers/serial.cpp.o
.PHONY : src/kernel/drivers/serial.cpp.o

src/kernel/drivers/serial.i: src/kernel/drivers/serial.cpp.i

.PHONY : src/kernel/drivers/serial.i

# target to preprocess a source file
src/kernel/drivers/serial.cpp.i:
	$(MAKE) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/kernel/drivers/serial.cpp.i
.PHONY : src/kernel/drivers/serial.cpp.i

src/kernel/drivers/serial.s: src/kernel/drivers/serial.cpp.s

.PHONY : src/kernel/drivers/serial.s

# target to generate assembly for a file
src/kernel/drivers/serial.cpp.s:
	$(MAKE) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/kernel/drivers/serial.cpp.s
.PHONY : src/kernel/drivers/serial.cpp.s

src/kernel/kentry.o: src/kernel/kentry.cpp.o

.PHONY : src/kernel/kentry.o

# target to build an object file
src/kernel/kentry.cpp.o:
	$(MAKE) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/kernel/kentry.cpp.o
.PHONY : src/kernel/kentry.cpp.o

src/kernel/kentry.i: src/kernel/kentry.cpp.i

.PHONY : src/kernel/kentry.i

# target to preprocess a source file
src/kernel/kentry.cpp.i:
	$(MAKE) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/kernel/kentry.cpp.i
.PHONY : src/kernel/kentry.cpp.i

src/kernel/kentry.s: src/kernel/kentry.cpp.s

.PHONY : src/kernel/kentry.s

# target to generate assembly for a file
src/kernel/kentry.cpp.s:
	$(MAKE) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/kernel/kentry.cpp.s
.PHONY : src/kernel/kentry.cpp.s

src/kernel/kprint.o: src/kernel/kprint.cpp.o

.PHONY : src/kernel/kprint.o

# target to build an object file
src/kernel/kprint.cpp.o:
	$(MAKE) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/kernel/kprint.cpp.o
.PHONY : src/kernel/kprint.cpp.o

src/kernel/kprint.i: src/kernel/kprint.cpp.i

.PHONY : src/kernel/kprint.i

# target to preprocess a source file
src/kernel/kprint.cpp.i:
	$(MAKE) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/kernel/kprint.cpp.i
.PHONY : src/kernel/kprint.cpp.i

src/kernel/kprint.s: src/kernel/kprint.cpp.s

.PHONY : src/kernel/kprint.s

# target to generate assembly for a file
src/kernel/kprint.cpp.s:
	$(MAKE) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/kernel/kprint.cpp.s
.PHONY : src/kernel/kprint.cpp.s

src/kernel/string.o: src/kernel/string.cpp.o

.PHONY : src/kernel/string.o

# target to build an object file
src/kernel/string.cpp.o:
	$(MAKE) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/kernel/string.cpp.o
.PHONY : src/kernel/string.cpp.o

src/kernel/string.i: src/kernel/string.cpp.i

.PHONY : src/kernel/string.i

# target to preprocess a source file
src/kernel/string.cpp.i:
	$(MAKE) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/kernel/string.cpp.i
.PHONY : src/kernel/string.cpp.i

src/kernel/string.s: src/kernel/string.cpp.s

.PHONY : src/kernel/string.s

# target to generate assembly for a file
src/kernel/string.cpp.s:
	$(MAKE) -f CMakeFiles/kernel.dir/build.make CMakeFiles/kernel.dir/src/kernel/string.cpp.s
.PHONY : src/kernel/string.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... kernel"
	@echo "... src/kernel/IDT/IDT.o"
	@echo "... src/kernel/IDT/IDT.i"
	@echo "... src/kernel/IDT/IDT.s"
	@echo "... src/kernel/IDT/Keyboard/KBScanCode.o"
	@echo "... src/kernel/IDT/Keyboard/KBScanCode.i"
	@echo "... src/kernel/IDT/Keyboard/KBScanCode.s"
	@echo "... src/kernel/IDT/Keyboard/Keyboard.o"
	@echo "... src/kernel/IDT/Keyboard/Keyboard.i"
	@echo "... src/kernel/IDT/Keyboard/Keyboard.s"
	@echo "... src/kernel/IO.o"
	@echo "... src/kernel/IO.i"
	@echo "... src/kernel/IO.s"
	@echo "... src/kernel/MEM/Heap.o"
	@echo "... src/kernel/MEM/Heap.i"
	@echo "... src/kernel/MEM/Heap.s"
	@echo "... src/kernel/MEM/Memory.o"
	@echo "... src/kernel/MEM/Memory.i"
	@echo "... src/kernel/MEM/Memory.s"
	@echo "... src/kernel/MEM/MemoryMap.o"
	@echo "... src/kernel/MEM/MemoryMap.i"
	@echo "... src/kernel/MEM/MemoryMap.s"
	@echo "... src/kernel/cpu/8259.o"
	@echo "... src/kernel/cpu/8259.i"
	@echo "... src/kernel/cpu/8259.s"
	@echo "... src/kernel/cpu/cpuid.o"
	@echo "... src/kernel/cpu/cpuid.i"
	@echo "... src/kernel/cpu/cpuid.s"
	@echo "... src/kernel/drivers/cmos.o"
	@echo "... src/kernel/drivers/cmos.i"
	@echo "... src/kernel/drivers/cmos.s"
	@echo "... src/kernel/drivers/fs/disks.o"
	@echo "... src/kernel/drivers/fs/disks.i"
	@echo "... src/kernel/drivers/fs/disks.s"
	@echo "... src/kernel/drivers/fs/floppy.o"
	@echo "... src/kernel/drivers/fs/floppy.i"
	@echo "... src/kernel/drivers/fs/floppy.s"
	@echo "... src/kernel/drivers/pit.o"
	@echo "... src/kernel/drivers/pit.i"
	@echo "... src/kernel/drivers/pit.s"
	@echo "... src/kernel/drivers/serial.o"
	@echo "... src/kernel/drivers/serial.i"
	@echo "... src/kernel/drivers/serial.s"
	@echo "... src/kernel/kentry.o"
	@echo "... src/kernel/kentry.i"
	@echo "... src/kernel/kentry.s"
	@echo "... src/kernel/kprint.o"
	@echo "... src/kernel/kprint.i"
	@echo "... src/kernel/kprint.s"
	@echo "... src/kernel/string.o"
	@echo "... src/kernel/string.i"
	@echo "... src/kernel/string.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

