#define VGA_MEMORY (unsigned char*) 0xb8000

#define VGA_WIDTH 80

//VGA Colors TODO: Moving to enum

//Background
#define FOREGROUND_BLACK 0x00
#define FOREGROUND_BLUE 0x01
#define FOREGROUND_GREEN 0x02
#define FOREGROUND_CYAN 0x03
#define FOREGROUND_RED 0x04
#define FOREGROUND_MAGENTA 0x05
#define FOREGROUND_BROWN 0x06
#define FOREGROUND_LIGHTGRAY 0x07
#define FOREGROUND_DARKGRAY 0x08
#define FOREGROUND_LIGHTBLUE 0x09
#define FOREGROUND_LIGHTGREEN 0x0A
#define FOREGROUND_LIGHTCYAN 0x0B
#define FOREGROUND_LIGHTRED 0x0C
#define FOREGROUND_LIGHTMAGENTA 0x0D
#define FOREGROUND_YELLOW 0x0E
#define FOREGROUND_WHYTE 0x0F

//Foreground
#define BACKGROUND_BLACK 0x00
#define BACKGROUND_BLUE 0x10
#define BACKGROUND_GREEN 0x20
#define BACKGROUND_CYAN 0x30
#define BACKGROUND_RED 0x40
#define BACKGROUND_MAGENTA 0x50
#define BACKGROUND_BROWN 0x60
#define BACKGROUND_LIGHTGRAY 0x70
#define BACKGROUND_BLICKINBLACK 0x80
#define BACKGROUND_BLICKINBLUE 0x90
#define BACKGROUND_BLICKINGREEN 0xA0
#define BACKGROUND_BLICKINCYAN 0xB0
#define BACKGROUND_BLICKINRED 0xC0
#define BACKGROUND_BLICKINMAGENTA 0xD0
#define BACKGROUND_BLICKINYELLOW 0xE0
#define BACKGROUND_BLICKINWHYTE 0xF0
